name = input("Enter your name: ")
age = input("Enter your age: ")
cgpa = input("Enter your cgpa: ")

print()
print("Student Information")
print("-------------------")
print("Name : " + name)
print("age : " + age)
print("cgpa : " + cgpa)